Algoritmo "armazenamento"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/02/2023
var
 n,a,b :real
 inicio
 escreval("Digite um numero")
 leia (n)
 se ( n>=0) entao
 a <- n
 
 escreval("O numero",a, "é variavel de A")
 
 senao
 b <- n
 escreval ("O numero",b, "é variavel de B")
 
 
 
 
 
 
fimse
fimalgoritmo