Algoritmo "Faixa Permitida"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/02/2023
Var
n:real
inicio
escreval("Digite um valor:")
leia (n)
se (n >=1) e (n <=9) entao
escreval ("O valor esta na faixa permitida")
senao
escreval("O valor não está na faixa permitida")
fimse

fimalgoritmo

