Algoritmo "par ou ímpar"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/02/2023
Var
N:Inteiro
Inicio
Escreval ("Insira um número inteiro")
leia (N)
se(N mod 2 = 0)entao
escreval("O numero:" ,N, " é par")
senao
escreval("O numero:" ,N, "é ímpar")
fimse
fimalgoritmo
